quotes = [
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "The secret of getting ahead is getting started. - Mark Twain",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "In the middle of difficulty lies opportunity. - Albert Einstein",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "It's not whether you get knocked down, it's whether you get up. - Vince Lombardi",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "Don't let yesterday take up too much of today. - Will Rogers",
    "The best revenge is massive success. - Frank Sinatra",
    "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
    "I am thankful for my struggle because without it, I wouldn’t have stumbled upon my strength. - Alex Elle",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Dream big and dare to fail. - Norman Vaughan",
    "It always seems impossible until it's done. - Nelson Mandela",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The harder you work for something, the greater you'll feel when you achieve it. - Anonymous",
    "Push yourself, because no one else is going to do it for you. - Anonymous",
    "The comeback is always stronger than the setback. - Anonymous",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "Don’t stop when you’re tired. Stop when you’re done. - Anonymous",
    "Do what you have to do until you can do what you want to do. - Oprah Winfrey",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it. - Jordan Belfort",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence. - Confucius",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Don’t watch the clock; do what it does. Keep going. - Sam Levenson",
    "Failure is the condiment that gives success its flavor. - Truman Capote",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "Don't let yesterday take up too much of today. - Will Rogers",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis"
]
